
import { createClient } from '@supabase/supabase-js';

// ============================================================================
// !!! CRITICAL DATABASE FIX !!!
// If you see the error: 'violates foreign key constraint "chat_messages_id_fkey"'
// RUN THE FOLLOWING SQL IN YOUR SUPABASE SQL EDITOR IMMEDIATELY:
// ============================================================================
/*

ALTER TABLE public.chat_messages DROP CONSTRAINT IF EXISTS chat_messages_id_fkey;

-- If you haven't created the tables yet, use the full schema below.
*/

// ============================================================================
// SUPABASE CONFIGURATION
// ============================================================================

// Helper to safely access environment variables
const getEnv = (key: string) => {
    try {
        if (typeof process !== 'undefined' && process.env && process.env[key]) {
            return process.env[key];
        }
        // @ts-ignore
        if (typeof import.meta !== 'undefined' && import.meta.env && import.meta.env[key]) {
             // @ts-ignore
            return import.meta.env[key];
        }
    } catch (e) {
        return undefined;
    }
    return undefined;
};

// TRY TO LOAD FROM ENV, ELSE FALLBACK TO DEMO KEYS (Replace these!)
const supabaseUrl = getEnv('VITE_SUPABASE_URL') || getEnv('REACT_APP_SUPABASE_URL') || 'https://mogdizazsjmlrtdsqxfl.supabase.co';
const supabaseKey = getEnv('VITE_SUPABASE_ANON_KEY') || getEnv('REACT_APP_SUPABASE_ANON_KEY') || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vZ2RpemF6c2ptbHJ0ZHNxeGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NjYyNDQsImV4cCI6MjA4MDM0MjI0NH0.JIaIAY_MboM8pQHiB3Ij9LHEzrJDUngnx5BJ8bcErPE';

export const supabase = createClient(supabaseUrl, supabaseKey);

/*
-- FULL DATABASE SCHEMA (Run this if starting fresh)

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.chats (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_email text NOT NULL,
  status text DEFAULT 'open',
  assigned_agent_id uuid REFERENCES auth.users,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  chat_id uuid REFERENCES public.chats ON DELETE CASCADE,
  message_text text NOT NULL,
  sender_type text NOT NULL, -- 'user', 'agent', 'system', 'ai'
  sender_id uuid, -- Nullable for guests/system/ai
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  subject text,
  message text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name text,
  email text,
  role text DEFAULT 'Employee',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  type text,
  image text,
  overview text,
  challenges text,
  approach text,
  results text,
  technologies jsonb,
  created_at timestamptz DEFAULT now()
);

-- 2. Enable RLS
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies

-- CHATS
CREATE POLICY "Public insert chats" ON public.chats FOR INSERT WITH CHECK (true);
CREATE POLICY "Public select chats" ON public.chats FOR SELECT USING (true);
CREATE POLICY "Public update chats" ON public.chats FOR UPDATE USING (true);

-- MESSAGES
CREATE POLICY "Public insert chat_messages" ON public.chat_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Public select chat_messages" ON public.chat_messages FOR SELECT USING (true);

-- INQUIRIES
CREATE POLICY "Public insert inquiries" ON public.inquiries FOR INSERT WITH CHECK (true);

-- PROFILES
CREATE POLICY "Public read profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- PROJECTS
CREATE POLICY "Public read projects" ON public.projects FOR SELECT USING (true);
*/
